### ISSUE TITLE
Locked cards say "Unknown" instead of "Locked" in the library

### ISSUE THREAD

**Issue by lionpkqq** [daviscook477/BaseMod#120]
As title. Only happens to modded characters.

**Comment by kiooeht** [comment]
Are you sure? "Unknown" is for when a card is unlocked but not seen and as far as I can tell from looking at the game's code, that's the only way it should be able to say "Unknown" instead of "Locked".

**Comment by lionpkqq** [comment]
Here is what I did and observed: 
I locked certain cards by doing `// servant unlock 1
		BaseMod.addUnlockBundle(new CustomUnlockBundle(
				"Manipulate", "Moondial", "Enbodiment"
				), TheServantEnum.THE_SERVANT, 1);
		UnlockTracker.addCard("Manipulate");
		UnlockTracker.addCard("Moondial");
		UnlockTracker.addCard("Enbodiment");`
Then I deleted everything in the Preferences folder, and restarted the game.
The card library was not accessible because I just deleted my saves so I started an Ironclad game and abandoned the game right away.
Then I looked into the card library and found the cards at the bottom of the library and said "Unknown".

![20180830165016](https://user-images.githubusercontent.com/33392240/44885295-e0a69f00-ac74-11e8-9e6e-ba842f99aa1b.png)

Then I used the relic Orrery to test if any of these cards were actually unlocked. They were not.

**Comment by kiooeht** [comment]
You're currently unlocking every card in `receiveEditCards`, did you get rid of that?

**Comment by lionpkqq** [comment]
Yes, of course. What i have left is BaseMod.addCard(new Strike_Silver()); and alike.

**Comment by kiooeht** [comment]
It looks like all the locked cards and relics are hardcoded. You can see them in `UnlockTracker.refresh()`.

I'll fix it to work with the CustomUnlockBundle, but no promises that it will make it in before today's update.

**Comment by kiooeht** [comment]
OK, there's a `SetUnlocksSubscriber` hook for this exact thing. Just call `UnlockTracker.addCard` and/or `UnlockTracker.addRelic` in the `receiveSetUnlocks` from that hook and you should be good.

**Comment by lionpkqq** [comment]
> OK, there's a `SetUnlocksSubscriber` hook for this exact thing. Just call `UnlockTracker.addCard` and/or `UnlockTracker.addRelic` in the `receiveSetUnlocks` from that hook and you should be good.

I have already done this when I submitted this issue and it did not work.

**Comment by Seeonee** [comment]
I believe I've found the issue with this as well as the fix. I'm a bit new to contributing on GitHub so I'm still figuring out how to issue a pull request.

Anyways, I think the issue lies in basemod.patches.com.megacrit.cardcrawl.screens.compendium.CardLibraryScreen.EverythingFix.setLockStatus#Postfix

Lines 81-82 look like this:
`                    CardGroup group = new CardGroup(CardGroup.CardGroupType.UNSPECIFIED);
                    group.group = CardLibrary.getCardList(CardLibrary.LibraryType.valueOf(colors[icolor].name()));
`

...and should be replaced with this single line:
`                    CardGroup group = Fields.cardGroupMap.get(colors[icolor]);
`

Currently, new CardGroups are being built from the Library, instead of using the ones saved to basemod.patches.com.megacrit.cardcrawl.screens.compendium.CardLibraryScreen.EverythingFix.Fields#cardGroupMap.

These (new) groups are passed to com.megacrit.cardcrawl.screens.compendium.CardLibraryScreen#lockStatusHelper which does a lookup against the UnlockTracker, removes certain cards, and adds locked copies. Since the groups are then discarded and no changes are ever made to the cardGroupMap groups, those don't reflect the lock changes when they're displayed later by com.megacrit.cardcrawl.screens.compendium.CardLibraryScreen#open

**Comment by kiooeht** [comment]
Fixed by #203.
