### ISSUE TITLE
NullPointerException with CustomRelic

### ISSUE THREAD

**Issue by GreatThane** [daviscook477/BaseMod#151]
I'm not sure if it's me (I'm new to ModTheSpire and BaseMod, but have a fair amount of Java experience), but I'm unable to make a new CustomRelic without it returning null. Here's my [project file](https://github.com/GreatThane/ApotheosisEgg/blob/master/src/main/java/org/thane/ApotheosisEgg.java).
I've followed along with both the examples provided and a few other mods which add relics to the game.
Here is the stack trace:

04:55:44.591 INFO thane.ApotheosisEggMod> false
04:55:44.591 INFO thane.ApotheosisEggMod> false
04:55:44.591 INFO thane.ApotheosisEggMod> false
04:55:44.592 INFO thane.ApotheosisEggMod> false
04:55:44.592 INFO thane.ApotheosisEggMod> false
Exception: java.lang.NullPointerException
04:55:44.597 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.relics.AbstractRelic.<init>(AbstractRelic.java:124) ~[?:?]
	at basemod.abstracts.CustomRelic.<init>(CustomRelic.java:10) ~[BaseMod.jar:?]
	at org.thane.ApotheosisEgg.<init>(ApotheosisEgg.java:28) ~[ApotheosisEgg.jar:?]
	at org.thane.ApotheosisEggMod.receiveEditRelics(ApotheosisEggMod.java:60) ~[ApotheosisEgg.jar:?]
	at basemod.BaseMod.publishEditRelics(BaseMod.java:2171) ~[?:?]
	at basemod.patches.com.megacrit.cardcrawl.helpers.RelicLibrary.EditRelicsPatch.Prefix(EditRelicsPatch.java:11) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.helpers.RelicLibrary.initialize(RelicLibrary.java) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:285) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [SlayTheSpire.jar:?]
04:55:44.641 INFO basemod.ModBadge> initialized mod badge for: BaseMod
04:55:44.642 INFO basemod.ModBadge> setup hooks for BaseMod mod badge
Game closed.

Following it through all the way back to AbstractRelic, I think the issue may have to do with the line
`this.description = this.getUpdatedDescription();`
which goes all the way back up to my own method (which all the wiki pages say is that it uses localization files but there's no more explanation past that, so I've had to go off of examples for that so [I may not be formatting it correctly](https://github.com/GreatThane/ApotheosisEgg/blob/master/src/main/resources/localization/relics.json)).
Assuming my localization files are incorrectly formatted, I believe some sort of clear explanation for how these files should be formatted and how they work or a fix for the CustomRelic / a friendly little patch for AbstractRelic.

**Comment by kiooeht** [comment]
Your localization files are formatted correctly, the problem is the file path.

No two mods are able to have files with exactly the same path, only one of the mod's files will be accessible. In your case, your relic localization file is at `localization/relics.json`. Given the incredible likelihood that a mod would try to name their relic localization file `localization/relics.json`, BaseMod defines it already to stop any mod from trying to use that path.

The solution is simple: Rename your localization files. A good system is to move all your resource files into a subdirectory named after your mod. For example, Hubris puts them all under `hubrisAssets` (https://github.com/kiooeht/Hubris/tree/master/src/main/resources) and Mystic puts them all under `mysticmod` (https://github.com/JohnnyDevo/The-Mystic-Project/tree/master/src/main/resources).
