### ISSUE TITLE
StartGameSubscriber is never publishing

### ISSUE THREAD

**Issue by girogore** [daviscook477/BaseMod#33]
publishPreStartGame shows up in the log, but publishStartGame never does.

**Comment by daviscook477** [comment]
Confirmed bug. Will fix.

**Comment by daviscook477** [comment]
Looks like when I originally added `StartGameSubscriber` to the API it never actually did anything because it hooks into an unused method. I'm not sure if I should deprecate the method, remove it from the API, or actually make it do something. For now just use `PreStartGameSubscriber` since it performs the intended function of `StartGameSubscriber`.

**Comment by daviscook477** [comment]
I'm going to leave this open until I figure out what to do with this part of the API.

**Comment by daviscook477** [comment]
So what may have happened is the method that `StartGameSubscriber` hooks into may have been used and then the devs refactored things so I'm going to figure out where `StartGameSubscriber` should go into to properly notify mods about the same time as they used to7

**Comment by daviscook477** [comment]
Fixed
