### ISSUE TITLE
Game crash on start-up before menu

### ISSUE THREAD

**Issue by Asger91** [daviscook477/BaseMod#58]
Since the newest Update (Beta and non Beta build) the game crashes right before it gets to the menu, after the Megacrit screen.
It only happens if you have a character mod checked in the Modloader.

Here is a picture of it,

![untitled](https://user-images.githubusercontent.com/38844325/39411743-b0492f04-4c10-11e8-8960-20c23319d77a.png)

**Comment by GraysonnG** [comment]
Necromancer is not updated to the latest build, only a few characters will work until people update. 
I would make sure these things are the latest version:
* [BaseMod (2.7.0) Week 22 Patch](https://github.com/daviscook477/BaseMod/releases/tag/v2.7.0-pre)
* [ModTheSpire (2.6.0)](https://github.com/kiooeht/ModTheSpire/releases/tag/v2.6.0)
* And since week 22 the mods need to be updated to support changes made by the developers.

**Comment by daviscook477** [comment]
@Asger91 the latest update broke all mods so even though BaseMod is up to date we need to wait for new versions of the mods themselves to come out

**Comment by Asger91** [comment]
Yeah I have all up to date, as far as released.
And I have seen this myself.
But thanks for the replies. :)
